FROM jenkins/jenkins:latest

USER root

# Install Python 3, python3-venv package, and pip
RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip && \
    apt-get clean

# Install pipx
RUN python3 -m pip install flask


USER jenkins
