FROM jenkins/jenkins:latest

USER root

# Install Python 3, python3-venv package, and pip
RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip && \
    apt-get clean

# Create a virtual environment
RUN python3 -m venv /opt/venv

# Activate the virtual environment and install pipx
RUN /opt/venv/bin/python -m pip install pipx

USER jenkins
